name: Persistent VPS
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y screen tmux neofetch openssh-server ufw

      - name: Configure SSH Server
        run: |
          echo "root:github123" | sudo chpasswd
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          echo "Port 22" | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl restart ssh
          sudo systemctl enable ssh

      - name: Open Firewall for SSH
        run: |
          sudo ufw allow 22/tcp
          sudo ufw --force enable
          sudo ufw reload

      - name: Show Public IP
        run: curl ifconfig.me

      - name: Keep VPS Alive
        run: |
          screen -dmS vps bash -c 'while true; do echo "VPS Running..."; sleep 3600; done'
      
      - name: Prevent Auto-Termination
        run: |
          while true; do echo "Still alive at $(date)"; sleep 300; done
